# DATA CLEANING AND PREPARATION
<a id='pres-title'></a>

## Table of content
* [I. INTRODUCTION](#introduction)
* [II. DATA WRANGLING, MUNGLING](#data-wrangling-munging)
* [III. TIDY DATA](#tidy-data)
* [IV. NUMPY](#numpy)
* [V. PANDAS](#pandas)
* [VI. DATA CLEANING WITH PANDAS](#data-cleaning)
* [VII. TIDY DATA WITH PANDAS](#tidy-data-with-pandas)

# I. INTRODUCTION
<a id="introduction"></a>
___

## ▸ Main objectives
___
* To understand why **data preparation** is a crucial step
* To get acquainted with the two workhorses of data wrangling: **NumPy** and **Pandas**
* To be able to implement **all key operations of data pre-processing**

### References
* Companion notebook: FM7/notebooks/3-data-cleaning-and-preparation.ipynb
* Python for Data Analysis, Wes MacKinney, OReilly: https://github.com/wesm/pydata-book 
* http://pandas.pydata.org/pandas-docs/stable/tutorials.html


### Notes
* One of the important objective is to be up and running on both NumPy and Pandas as used extensively in the rest of the course
* Wes MacKinney is the author and main developer of Pandas package

## ▸ Keep data alive
___
* There is **no ideal structure** for data
* All **depends on purpose** of use
* BUT in all cases, every cleaning or transformation steps should be **reproducible and automated**

### References
* Reproducible Research in Computational Science Roger D. Peng (see FM7/references)

### Notes
* Again, data is just data! There are many perspectives you may consider depending on problem to solve, domain-knowledge, ... 
* Consider data as a dynamic flow that you can refine in various way depending on the situation

# II. DATA WRANGLING, MUNGLING
___
<a id="data-wrangling-munging"></a>

> … is the process of transforming and mapping data from one “raw” data form into another format with the intent of making it  more appropriate and valuable for a variety of downstream purposes such as analytics” 

https://en.wikipedia.org/wiki/Data_wrangling

## ▸ What is "raw", primary data?
___

* **Data collected from a source** (for instance a sensor, data entry clerk, …)
* Has **not been subject to prior processing**
* **BUT IS RELATIVE**: data constantly re-aligned to analysis, predictive goals 


### Notes
* Ex: Temperature sensors sending data -> might have systematic bias that could be corrected based on other stations, … detection errors mechanism (checksum) might reveal that some of the data transmitter are corrupted, so need to remove them, …
* Data entry clercks and spelling mistakes, …
* Prior processing: automatically by a program, manually by an analyst, researcher, …
* Depending pre-processed data (clean , reshaped, …) for one purpose might not be suitable for another one. In reality, data should be considered as a living entity rather than something set in stone, constantly re-aligned to the needs (that’s reflected by the variety of techniques  in data wrangling, versatility of tools, and Big Data tool ecosystem as well)

## ▸ Some typical data cleaning tasks
___

* Handling **missing data**
* Handling **duplicate data**
* String manipulation (to fix typos, ...)
* ...

### Notes
* Some others: removing data transmitted with bad checksums, defining appropriate data types, ...

## ▸ Some typical data preparation tasks
___

* Replacing values, binning, indexing, combining, reshaping, ...
* Joining, merging, pivoting, stacking with quantitative data exploration in mind
* Creating dummy variables, reshaping to feed ML/DL algorithms
* Performing feature engineering

### Notes
* Pivot table should be familiar to you if you are an Excel user
* Feature engineering will be covered in subsequent courses and aims at transforming the original dataset to ease the learning process, ...

## ▸ Preliminary remarks
___

* Data cleaning and preparation is **often reported to take up 80% or more** of a data scientist’s time
* The whole process **MUST BE automated and reproducible**
* **NumPy** and **Pandas** are the two workhorses easing the whole process

### Notes
* This is not indeed the most exciting part of a data scientist’s daily work, however, we will introduce tools greatly facilitating the process and when dealing with a real dataset and eager to explore, discover new patterns, insights and eventually creating predictive model, … motivation comes!



## ▸ The two workhorses of data transformation
___

* **NumPy** : foundational packages for **numerical computing** in Python
* **Pandas**: contains data structures and data manipulation tools making data cleaning and analysis fast and easy

### References
* [http://www.numpy.org/](http://www.numpy.org/)
* [https://pandas.pydata.org/](https://pandas.pydata.org/)

### Notes
* NumPy, short of Numerical computing
* Pandas often used in tandem with Numpy
* Being proficient with both packages is a prerequisite for data science with Python


## ▸ Quiz 1: Why is data wrangling so crucial?
___
<a class='quiz-nb'></a>

1. It makes easier to store data into relational databases
2. It allows tailoring data to fit your specific needs
3. It allows "normalize" data acquired removing typos, handling missing data, removing duplicates, ...


### Notes
* Sort by importance
* The right answer is (might be open to dicussion): 2, 3, 1 

# III. TIDY DATA
___
<a id="tidy-data"></a>

![tidy-data-paper-screenshot.png](img/tidy-data-paper-screenshot.png)

## ▸ Tidy data
___

* a **standard way** to **organize data values** within a dataset
* in a way that **makes data analysis possible**
* standardized way to **link structure** of a dataset (its physical layout) with its **semantics**

### References

* Tidy Data, Hadley Wickham, Journal of Statistical Sosftware (FM7/references/tidy-data-wickham.pdf)

### Notes
* Hadley Wickham coined the term in his famous paper "Tidy Data". He is very famous within the R Software community for developing important packages such as ggplot, dplyr, ...
* Tidy data paper is a **must read!**

## ▸ Data structure
___

![data-structure.png](img/data-structure.png)


### References
* Tidy Data, Hadley Wickham, Journal of Statistical Sosftware (FM7/references/tidy-data-wickham.pdf)

### Notes
* Our vocabulary of rows and columns is simply not rich enough to describe why the two tables represent the same data
* Often people think that providing dataset grouped, pivoted as it can be done for instance for the sake of presentation of analysis in a spreadsheet software will help further data analysis. 

## ▸ Data semantics
___

![data-semantics.png](img/data-semantics.png)


### References
* Tidy Data, Hadley Wickham, Journal of Statistical Sosftware (FM7/references/tidy-data-wickham.pdf)

### Notes
* A dataset is a collection of **values**, usually either numbers (if quantitative) or strings (if qualitative)
* Values are organized in two ways. Every **value belongs** to a **variable** and an **observation**
* A **variable** contains all values that measure the same underlying attribute (like height, temperature, duration) across units
* An **observation** contains all values measured on the same unit (like a person, or a day, or a race) across attributes

## ▸ In Tidy data:
___

* Each **variable** forms a **column**
* Each **observation** forms a **row**
* Each type of **observational unit** forms a **table**

### References
* Tidy Data, Hadley Wickham, Journal of Statistical Sosftware (FM7/references/tidy-data-wickham.pdf)

### Notes
* The standardized way to **link structure** of a dataset (its physical layout) with its **semantics**
* **Observational units** are entities whose characteristics we measure
* Tidy data is only worthwhile if it makes analysis easier

## ▸ Pandas to the rescue
___

* H. Wickham implemented a **series of R packages** supporting his Tidy data vision
* Hopefully, **Pandas Python package allows to replicate** most of R tidyverse suite of packages functionalities
* So let's **dive in NumPy and Pandas**

### References
* Tidy Data, Hadley Wickham, Journal of Statistical Sosftware (FM7/references/tidy-data-wickham.pdf)

### Notes
* R packages dplyr is awesome and you should give it a try. It illustrates as well the fact mentionned already that a data scientist should be able to switch from one analytical platform to the other based on needs, environment, ...
* Actually in R, there are a suite of packages dubbed "tidyverse" including: lubridate, reshape2, stringr, plyr, ggplot, ... reflecting the whole "Tidy vision"
* We will come back to Tidy data once familiar with both Numpy and Pandas

## ▸ Quiz 2: What's the whole purpose of Tidy data
___
<a class='quiz-nb'></a>

1. To ease any further data processing and analysis
2. To define data sharing best practices
3. To ease collaboration and replication


### Notes
* Check the right answer(s)
* The right answers are: all of them 1,2,3

# IV. NUMPY
___
<a id="numpy"></a>

> Fundamental package for scientific computing with Python

## ▸ Why is NumPy so important?
___

* Efficient way to **handle large arrays** of data
* Most Python Data Science packages use NumPy’s array objects for **data exchange**
* Plays a **key role** not only in data transformation but as well in Machine Learning, Statistics, Deep Learning, … 

### Notes
* Pandas is based on NumPy
* NumPy arrays appear everywhere in ML and DL pipelines
* Numerical stability is critical for instance in Linear Algebra (at the core of Machine and Deep Learning). A package like Numpy, using state of the art techniques such as LAPACK routines, ... will be far more efficient than a Python naive approach (unless you are a master in numerical linear algebra ...)

## ▸ Main areas of functionality includes:
___

* Fast **vectorized** array manipulation
* **Indexing, selection, subsetting** datasets
* **Merging, joining** heterogeneous datasets
* Efficient **descriptive statistics**
* …
 

## ▸ NumPy Crash Course [Notebook Live Demo]
___
* To **create** NumPy arrays
* To understand NumPy arrays **main attributes**
* To Understand important **Vectorization** and **Broadcasting** notions
* To become proficient in **slicing, indexing, ...** arrays
* To harness powerful NumPy **utilities and universal functions**
* ...

### References
* [https://docs.scipy.org/doc/numpy-dev/user/quickstart.html](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* [https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html)

### Notes
* [Teacher] Dedicate 15-30 min to the code snippet below showing and executing code live
* [Student] Be sure to run and understand the following code snippets before answering module's assignment

####   *Creating a simple NumPy array*

In [2]:
# Aliasing numpy as np is a widely used convention
import numpy as np

# Creating from a built-in Python list
data = np.array([1, 4, 6])

print('type: ', type(data))
print('has shape: ', data.shape)
print('has dimension: ', data.ndim)

type:  <class 'numpy.ndarray'>
has shape:  (3,)
has dimension:  1


In [3]:
data

array([1, 4, 6])

#### *Creating a multidimensional array*

In [4]:
data = np.array([[1, 2, 3], [4, 5, 6]])

print('type: ', type(data))
print('has shape: ', data.shape)
print('has dimension: ', data.ndim)

type:  <class 'numpy.ndarray'>
has shape:  (2, 3)
has dimension:  2


In [5]:
data

array([[1, 2, 3],
       [4, 5, 6]])

#### *Elements of a ndarray have a type*

In [6]:
# You can specify element's type 
data = np.array([1.1, 4.3, 6.8], dtype=np.float64)
data.dtype

dtype('float64')

In [7]:
# and you can change (cast)
data = data.astype('int32')
data

array([1, 4, 6], dtype=int32)

#### *Many useful array creation functions*

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

#### *Arithmetic with NumPy Arrays*

In [11]:
arr = np.array([[1,3,5], [7,9,11]])
arr2 = np.array([[2,1,6], [8,10,112]])
arr

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [12]:
arr * arr

array([[  1,   9,  25],
       [ 49,  81, 121]])

In [13]:
arr + arr2

array([[  3,   4,  11],
       [ 15,  19, 123]])

In [14]:
arr > arr2

array([[False,  True, False],
       [False, False, False]])

#### *Vectorizing computation*

In [15]:
# Mean Error/Distance
def mean_dist(x, y):
    nx = len(x)
    result = 0.0
    for i in range(nx):
        result += x[i] - y[i] 
    return result / nx

In [16]:
x = np.random.randn(10000000)
y = np.random.randn(10000000)

In [21]:
# First 10 elements of x
x[:10]

array([ 1.65955249, -2.06319247,  1.1220584 , -0.7138224 , -0.42951368,
        2.10796741,  1.50361578, -0.85660817,  0.86726372,  2.2562762 ])

In [17]:
%timeit mean_dist(x, y)

3.86 s ± 57.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
%timeit (x - y).mean()

37.6 ms ± 899 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### *Introducing Broadcasting*

In [22]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
x = np.array([[1,2,3], [4,5,6]])
y = 99

print(x.shape)
x

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# Look how the value of 'y' is propagated to match
# x dimension. This is called 'Broadcasting'
x + y

array([[100, 101, 102],
       [103, 104, 105]])

#### *Basic Indexing and Slicing*

In [19]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[5]

5

In [25]:
arr[2:6]

array([], shape=(0, 3), dtype=int64)

In [26]:
# An assignement and broadcasting example
arr[7:] = 99
arr

array([[ 1,  3,  5],
       [ 7,  9, 11]])

#### *Indexing, slicing in n dimensions*

In [27]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
data[1,2]

5

In [30]:
data[0,:]

array([0, 1, 2])

In [31]:
data[:,1]

array([ 1,  4,  7, 10])

#### *Boolean indexing*

In [32]:
data = np.random.randn(2,3)
data

array([[-1.75973674, -0.10519063,  0.27907367],
       [-1.15790379, -0.27702088,  0.12030566]])

In [33]:
data < 0

array([[ True,  True, False],
       [ True,  True, False]])

In [34]:
data[data < 0]

array([-1.75973674, -0.10519063, -1.15790379, -0.27702088])

In [35]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.27907367],
       [0.        , 0.        , 0.12030566]])

#### *Universal NumPy functions*

In [36]:
arr = np.array([1,9,25,36])

In [37]:
print(np.sqrt(arr))
print(np.square(arr))

[1. 3. 5. 6.]
[   1   81  625 1296]


In [39]:
x = np.random.randn(2,3)
y = np.random.randn(2,3)

# Take the maximum element-wise
np.maximum(x, y)

array([[0.22444877, 0.55003635, 1.08146311],
       [0.23278076, 0.66100345, 0.08906768]])

#### *Mathematical and Statistical methods*

In [40]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [41]:
arr.mean()

2.5

In [42]:
arr.mean(axis=1) # along the columns

array([1.5, 3.5])

In [43]:
arr.mean(axis=0) # along the rows

array([2., 3.])

## ▸ What about heterogeneous data types?
___

* **NumPy** is best suited for **homogeneous** numerical array data
* But Dataset often comes with **various attributes**: time, name, mesurements, …
* Based on NumPy, the **Pandas** package is designed for working with **heterogeneous** data


## ▸ Quiz 3: NumPy
___
<a class='quiz-nb'></a>

1. What's the most important data type in NumPy?
2. What's the purpose of vectorization?
3. What's the shape of array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8]])?
4. Is Numpy extensively used in machine and deep learning?

## ▸ Answer
___

##### ▸ Exercise 3: NumPy
___
1. Generate two numpy arrays filled with 1000 random numbers
2. Calculate the RMS (Root Mean Square) error https://en.wikipedia.org/wiki/Root-mean-square_deviation

## ▸ Answer
___

# V. PANDAS
<a id="pandas"></a>
___
> High-performance, easy-to-use data structures and data analysis tools with Python

https://pandas.pydata.org/

## ▸ Pandas toolbox
___

* Abstract and convenient Data Structures for data cleaning and preparation
* Data selection, indexing, visualization, aggregation, merging, reshaping, ...
* Time Series dedicated utilities
* ...

### References
* http://pandas.pydata.org/pandas-docs/stable/
* http://pandas.pydata.org/pandas-docs/stable/tutorials.html

### Notes
* This is essentially your Swiss knife for data science

## ▸ Pandas Data Structures
___

* **Based on Numpy array**
* **Series**: a one-dimensional array-like (somewhat similar to NumPy array)
* **DataFrame**: represent a “rectangular” table of data and can be thought of as a dict of **Series**

### References
* http://pandas.pydata.org/pandas-docs/stable/dsintro.html

## ▸ Pandas Crash Course [Notebook Live Demo]
___
 
* **Pandas Series**: creating, indexing, subsetting, aligning, missing values
* **Pandas DataFrame**: creating, updating, appending,
* **Pandas essential functionalities**: reindexing, dropping entries, function applications, ...

### References
* http://pandas.pydata.org/pandas-docs/stable/tutorials.html

### Notes
* [Teacher] Dedicate 30-45 min to the code snippet below showing and executing code live
* [Student] Be sure to run and understand the following code snippets before answering module's assignment

#### Pandas Series value and index

In [44]:
np.array([2, 4, 6])

array([2, 4, 6])

In [45]:
import pandas as pd
obj = pd.Series([2, 4, 6])
obj

0    2
1    4
2    6
dtype: int64

In [46]:
obj.values # is a NumPy array 

array([2, 4, 6])

In [47]:
obj.index # arrays of data labels

RangeIndex(start=0, stop=3, step=1)

#### Create a Series with its index

In [50]:
obj = pd.Series([2,5,6], index=['d','a','b'])
obj

d    2
a    5
b    6
dtype: int64

In [51]:
# You can index a Series using its ... index labels
obj['a']

5

In [52]:
obj[['a', 'd']]

a    5
d    2
dtype: int64

#### Subsetting in NumPy style

In [53]:
obj = pd.Series([-2,5,6,-4],index=['d','a','b','c'])
obj

d   -2
a    5
b    6
c   -4
dtype: int64

In [54]:
# As values are one-dimensional NumPy array, we
# can use the same subsetting techniques.
obj[obj > 0]

a    5
b    6
dtype: int64

#### Series killer feature: data alignment

In [55]:
pd.Series([2,5,6],index=['d','a','b'])

d    2
a    5
b    6
dtype: int64

In [56]:
pd.Series([-6,3,5,8],index=['d','a','c','e'])

d   -6
a    3
c    5
e    8
dtype: int64

In [57]:
obj1 = pd.Series([2,5,6],index=['d','a','b'])
obj2 = pd.Series([-6,3,5,8],index=['d','a','c','e'])

In [58]:
# Automatically align by data index
obj3 = obj1 + obj2
obj3

a    8.0
b    NaN
c    NaN
d   -4.0
e    NaN
dtype: float64

#### Removing missing values

In [59]:
obj3

a    8.0
b    NaN
c    NaN
d   -4.0
e    NaN
dtype: float64

In [60]:
# Quick and self-explanatory
obj3.dropna()

a    8.0
d   -4.0
dtype: float64

In [61]:
# Perfectly fine but less clear
# Note the ~ to negate Boolean values
obj3[~pd.isnull(obj3)]

a    8.0
d   -4.0
dtype: float64

#### Pandas DataFrame type
* Represent data in a **“tabular”** form;
* With ordered **columns of various types**;
* With both **row and columns having index**.

#### Creating a DataFrame

In [62]:
# From a dictionary of list
data = {'station': ['river', 'farm', 'road'],
        'year': ['2015', '2015', '2016'],
        'temperature': [23.3, 21.5, 27.9]}

df = pd.DataFrame(data)

In [63]:
# Display the 5 first rows
df.head()

station  year  temperature
0   river  2015         23.3
1    farm  2015         21.5
2    road  2016         27.9

#### DataFrame dissection

In [64]:
df.head()

station  year  temperature
0   river  2015         23.3
1    farm  2015         21.5
2    road  2016         27.9

In [65]:
# Row index
df.index

RangeIndex(start=0, stop=3, step=1)

In [66]:
# Column index
df.columns

Index(['station', 'year', 'temperature'], dtype='object')

In [67]:
# Each column is a Pandas Series
type(df['temperature'])

pandas.core.series.Series

#### Updating DataFrame index

In [68]:
# Updating column index
df.columns = ['Stat', 'Temp', 'Year']
df

Stat  Temp  Year
0  river  2015  23.3
1   farm  2015  21.5
2   road  2016  27.9

In [69]:
df.index = [14, 3, 8]
df

Stat  Temp  Year
14  river  2015  23.3
3    farm  2015  21.5
8    road  2016  27.9

#### Accessing columns and values

In [70]:
# From a dictionary of list
data = {'station': ['river', 'farm', 'road'],
        'year': ['2015', '2015', '2016'],
        'temperature': [23.3, 21.5, 27.9]}

df = pd.DataFrame(data)

In [71]:
df.head()

station  year  temperature
0   river  2015         23.3
1    farm  2015         21.5
2    road  2016         27.9

In [72]:
# Accessing a single column as Series
df.temperature
# or 
df['temperature'] # if space in name

0    23.3
1    21.5
2    27.9
Name: temperature, dtype: float64

In [73]:
# Accessing values as NumPy array
df.temperature.values

array([23.3, 21.5, 27.9])

#### Assigning values to a column

In [74]:
df.temperature = [11.2, 8.6, 16.3]
df.head()

station  year  temperature
0   river  2015         11.2
1    farm  2015          8.6
2    road  2016         16.3

In [75]:
df.temperature = (df.temperature / 1.2)
df.head()

station  year  temperature
0   river  2015     9.333333
1    farm  2015     7.166667
2    road  2016    13.583333

#### Appending a new column

In [76]:
# From a Series
altitude = pd.Series([34, 23], index=[0,2])
altitude

0    34
2    23
dtype: int64

In [77]:
df['altitude'] = altitude
df.head()

station  year  temperature  altitude
0   river  2015     9.333333      34.0
1    farm  2015     7.166667       NaN
2    road  2016    13.583333      23.0

#### Pandas essential functionalities
* Reindexing
* Dropping entries
* Selection and filtering
* Data alignment
* Function application

#### Reindexing

In [78]:
data = {'year': ['2015', '2015', '2016'],
        'temperature': [23.3, 21.5, 27.9]}
df = pd.DataFrame(data)

In [79]:
df.head()

year  temperature
0  2015         23.3
1  2015         21.5
2  2016         27.9

In [80]:
# Re-index dataframe based rearranged index
df2 = df.reindex([2,0,1])
df2.head()

year  temperature
2  2016         27.9
0  2015         23.3
1  2015         21.5

#### Dropping rows

In [81]:
data = {'year': ['2015', '2015', '2016'],
        'temperature': [23.3, 21.5, 27.9]}
df = pd.DataFrame(data, index=['a','b','c'])

In [82]:
df.head()

year  temperature
a  2015         23.3
b  2015         21.5
c  2016         27.9

In [83]:
# Drop a single row
# df.drop('c')
# or several
df2 = df.drop(['b', 'c'])

In [84]:
df2.head()

year  temperature
a  2015         23.3

#### Dropping columns

In [85]:
data = {'station': ['river', 'farm', 'road'],
        'year': ['2015', '2015', '2016'],
        'temperature': [23.3, 21.5, 27.9]}
df = pd.DataFrame(data, index=['a','b','c'])

In [86]:
df.head()

station  year  temperature
a   river  2015         23.3
b    farm  2015         21.5
c    road  2016         27.9

In [87]:
# Rows and columns are just different axis but
# can be handled symmetrically
df2 = df.drop('station', axis=1)
df2.head()

year  temperature
a  2015         23.3
b  2015         21.5
c  2016         27.9

#### Selecting with .loc and .iloc

In [89]:
data = {'station': ['river', 'farm', 'road'],
        'year': ['2015', '2015', '2016'],
        'temperature': [23.3, 21.5, 27.9]}
df = pd.DataFrame(data, index=['a','b','c'])

In [90]:
df.head()

station  year  temperature
a   river  2015         23.3
b    farm  2015         21.5
c    road  2016         27.9

In [91]:
# Select by label
df.loc[['a','c'],['station', 'year']]
# or select by integer (same result)
df.iloc[[0,2],[0, 1]]

station  year
a   river  2015
c    road  2016

#### Data Alignment

In [92]:
data = {'temperature': [12.2,34.3,20.9],
        'rain (mm)': [111,234,89]}
measurement = pd.DataFrame(data, index=['stat_a','stat_b', 'stat_c'])

In [93]:
data = {'temperature': [0.3,0.6],
        'rain (mm)': [9,11]}
calibration = pd.DataFrame(data, index=['stat_a','stat_b'])

In [94]:
measurement.head()

temperature  rain (mm)
stat_a         12.2        111
stat_b         34.3        234
stat_c         20.9         89

In [95]:
calibration.head()

temperature  rain (mm)
stat_a          0.3          9
stat_b          0.6         11

In [96]:
measurement + calibration
# Alignement is performed on both the rows and the columns

temperature  rain (mm)
stat_a         12.5      120.0
stat_b         34.9      245.0
stat_c          NaN        NaN

#### Function application

In [97]:
data = {'temperature': [12.2,34.3,20.9],
        'rain (mm)': [111,234,89]}
df = pd.DataFrame(data, index=['stat_a','stat_b', 'stat_c'])

In [98]:
df

temperature  rain (mm)
stat_a         12.2        111
stat_b         34.3        234
stat_c         20.9         89

In [99]:
def val_range(x):
    return x.max() - x.min()

df.apply(val_range)

temperature     22.1
rain (mm)      145.0
dtype: float64

In [100]:
# Or more succinctly using an anonymous (lambda)
# function
df.apply(lambda x: x.max() - x.min())

temperature     22.1
rain (mm)      145.0
dtype: float64

#### Pandas has much more to offer:
* Summarizing, computing statistics
* Accessing a large variety of data source (csv, web scrapping, …)
* Data pivoting, aggregation, visualization, …
* But you know the fundamentals now

## ▸ Quiz 4: Pandas
___
<a class='quiz-nb'></a>

1. What are axis?
2. What's the purpose of the ".loc" method?
3. What's the purpose of the ".iloc" method?
4. What's the most important data structure in Pandas?
5. What's the whole purpose of an index?

## ▸ Answer
___

# VI. DATA CLEANING WITH PANDAS
<a id="data-cleaning">
___

## ▸ The two main sides of data cleaning
___

* **Handling missing values**
* **Transforming data**: remove/update irrelevant or erroneous ones, data types, discretizing / binning, ...

### References
* http://pandas.pydata.org/pandas-docs/stable/missing_data.html

## ▸ Missing data
___

* A **very common situation** in many applications
* **Should be handled carefully** and in an informed way 
* Use a **Sentinel** value to be easily detected, **NA** (Not Available) but can be encoded as **NaN** (Not a Number) or **None**

### Notes
* Deciding to remove/ignore, fill based on available values missing values is an important and complex decision, let's take an example (see following slide)

## ▸ Is it missing data?
___

![is-it-missing-value.png](img/is-it-missing-value.png)

### References

* FM7/notebooks/use-cases/indoor-localization.ipynb

### Notes
* This is a use case where a device records at every time step the RSSIs (Relative Received Signal Strength) of WAP (Wireless Access Points) at a specific location. When RSSI for a WAP not detected is equal to 100. If your objective it to design an indoor location system based on RSSIs received, should you consider these values (100) are missing values?



## ▸ Data cleaning  [Notebook Live Demo]
___

* Encoding missing values: filtering, filling, 
* Transforming data: removing duplicates, modifying using function or lookup table, ...

### References
* http://pandas.pydata.org/pandas-docs/stable/tutorials.html

### Notes
* [Teacher] Dedicate 5-10 min to the code snippet below showing and executing code live
* [Student] Be sure to run and understand the following code snippets before answering module's assignment

#### Example of encoded missing values

In [101]:
data = pd.Series(['rwanda', 'nepal', np.nan])
data

0    rwanda
1     nepal
2       NaN
dtype: object

In [102]:
data.isnull()

0    False
1    False
2     True
dtype: bool

In [103]:
# None treated as NA
data[0] = None
data.isnull()

0     True
1    False
2     True
dtype: bool

#### Option 1: Filtering out NA

In [104]:
# For brevity's sake
from numpy import nan as NA

In [106]:
data = pd.Series([11, NA, 99])
data

0    11.0
1     NaN
2    99.0
dtype: float64

In [107]:
data.dropna() # or data[data.notnull()]

0    11.0
2    99.0
dtype: float64

In [108]:
# Removing NAs in a DataFrame
data = pd.DataFrame([[1, 2, NA], 
                     [NA, 3, 4], 
                     [9, 10, 11]])
data.head()

0   1     2
0  1.0   2   NaN
1  NaN   3   4.0
2  9.0  10  11.0

In [109]:
# Drop any rows containg at least a NaN
data.dropna()

0   1     2
2  9.0  10  11.0

#### Option 2: Filling in NA

In [110]:
data = pd.DataFrame([[1, 2, NA], 
                     [NA, 3, 4], 
                     [9, 10, 11]])

In [111]:
data.head()

0   1     2
0  1.0   2   NaN
1  NaN   3   4.0
2  9.0  10  11.0

In [112]:
# Replace NaN with 0
data.fillna(0)

0   1     2
0  1.0   2   0.0
1  0.0   3   4.0
2  9.0  10  11.0

In [113]:
# Choose wich filling value to use in which column
data.fillna({0:99, 2:-1})

0   1     2
0   1.0   2  -1.0
1  99.0   3   4.0
2   9.0  10  11.0

In [114]:
# or forward filling
data.fillna(method='ffill')

0   1     2
0  1.0   2   NaN
1  1.0   3   4.0
2  9.0  10  11.0

#### Removing duplicates

In [115]:
data = pd.DataFrame({'v1': [0,1,0,3], 
                     'v2': ['a','b','a','c']})

In [116]:
data.head()

v1 v2
0   0  a
1   1  b
2   0  a
3   3  c

In [117]:
data.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [118]:
data.drop_duplicates()

v1 v2
0   0  a
1   1  b
3   3  c

#### Updating using a lookup table

In [119]:
data = pd.DataFrame({'v1': [0,1,0], 
                     'v2': ['a','b','c']})

In [120]:
lookup = {'a': 'france', 'b': 'japan', 'c': 'italy'}

In [121]:
data['v2'] = data['v2'].map(lookup)

In [122]:
data

v1      v2
0   0  france
1   1   japan
2   0   italy

## ▸ Quiz 5
___
<a class='quiz-nb'></a>

1. Missing data should be systematically removed
2. Can missing data be meaningful information?
3. It is always relevant to fill missing data with the mean of all values

## ▸ Answer
___

## ▸ Exercise
___

1. Create a dataframe with the following structure:
    - a time column from '2018-01-01' to '2018-12-31'
    - a column named "temperature" with a random temperature (Normal distribution with mean 20°C and standard deviation of 10°C) over 2018
2. Set the "time" column as index
2. Plot the temperature vs. time

Hints:
* https://pandas.pydata.org/pandas-docs/stable/generated/pandas.date_range.html
* https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html
* https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.set_index.html

In [136]:
import matplotlib.pyplot as plt
%matplotlib inline  

# YOUR ANSWER HERE (ABOUT 5 lines of code)



# VII. TIDY DATA WITH PANDAS [OPTIONAL]
<a id="tidy-data-with-pandas"></a>
___

## ▸ Reproducing Tidy Data motivating example
___

![reproducing-tidy-dataset.png](img/reproducing-tidy-dataset.png)

### References
* http://pandas.pydata.org/pandas-docs/stable/tutorials.html

### Notes
* A simple dataframe with both columns and rows index

## ▸ Columns to rows to columns to rows ...
___

![stacking-circle.png](img/stacking-circle.png)

### References
* http://pandas.pydata.org/pandas-docs/stable/tutorials.html



## ▸ Making it tidy finally!
___

![tidy-treatment.png](img/tidy-treatment.png)

### References
* http://pandas.pydata.org/pandas-docs/stable/tutorials.html



## ▸ Tidying data with Pandas [Notebook Live Demo]
___
* Stacking, unstacking
* Pivoting and melting

### References
* http://pandas.pydata.org/pandas-docs/stable/tutorials.html

### Notes
* [Teacher] Dedicate 15-30 min to the code snippet below showing and executing code live
* [Student] Be sure to run and understand the following code snippets before answering module's assignment

#### Reproducing Tidy Data motivating example

In [110]:
from numpy import nan as NA
import pandas as pd

data = {'treatmenta': [NA, 16, 3],
        'treatmentb': [2, 11, 1]}

treatment = pd.DataFrame(data, 
                         index = pd.Index(['John Smith','Jane Doe','Mary Johnson'], 
                                          name='person'),
                         columns = pd.Index(['treatmenta', 'treatmentb'], 
                                            name='treatment'))

treatment

treatment     treatmenta  treatmentb
person                              
John Smith           NaN           2
Jane Doe            16.0          11
Mary Johnson         3.0           1

#### Stack, unstack, stack, unstack circle

In [111]:
treatment.stack()

person        treatment 
John Smith    treatmentb     2.0
Jane Doe      treatmenta    16.0
              treatmentb    11.0
Mary Johnson  treatmenta     3.0
              treatmentb     1.0
dtype: float64

In [112]:
treatment.stack().unstack('person')

person      John Smith  Jane Doe  Mary Johnson
treatment                                     
treatmenta         NaN      16.0           3.0
treatmentb         2.0      11.0           1.0

In [113]:
treatment.stack().unstack('person').stack()

treatment   person      
treatmenta  Jane Doe        16.0
            Mary Johnson     3.0
treatmentb  John Smith       2.0
            Jane Doe        11.0
            Mary Johnson     1.0
dtype: float64

In [114]:
treatment.stack().unstack('person').stack().unstack('treatment')

treatment     treatmenta  treatmentb
person                              
John Smith           NaN         2.0
Jane Doe            16.0        11.0
Mary Johnson         3.0         1.0

#### Finally tyding it!

In [115]:
tidy = treatment.stack().reset_index()
tidy.columns = ['person', 'treatment', 'value']
tidy

person   treatment  value
0    John Smith  treatmentb    2.0
1      Jane Doe  treatmenta   16.0
2      Jane Doe  treatmentb   11.0
3  Mary Johnson  treatmenta    3.0
4  Mary Johnson  treatmentb    1.0